FROM mcr.microsoft.com/playwright/python:v1.40.0-jammy

WORKDIR /app

# Instala dependencias de Python
RUN pip install requests flask playwright

# Copia el código
COPY app.py .

# Expone puerto
EXPOSE 5000

# Comando de ejecución
CMD ["python3", "app.py"]
