FROM mcr.microsoft.com/playwright/python:latest

WORKDIR /app

# Instala dependencias Python
RUN pip install flask playwright

# Instala navegadores (importante)
RUN playwright install --with-deps

COPY main.py .

EXPOSE 5000

CMD ["python", "main.py"]
